apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: teams-timetracker
  labels:
    app: teams-timetracker
spec:
  to:
    kind: Service
    name: teams-timetracker
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

# Made with Bob
