apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: timetracker-web
  labels:
    app: timetracker-web
    component: frontend
spec:
  to:
    kind: Service
    name: timetracker-web
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

# Made with Bob
